version: '3.8'

services:
  frontend:
    build: ./frontend
    restart: always
    command: npm run build && cp -r dist/* /app/dist/
    volumes:
      - frontend-build:/app/dist
    depends_on:
      - backend
    networks:
      - crm-network

  backend:
    build: ./backend
    restart: always
    ports:
      - "4000:4000"
      - "5555:5555"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/crm
    depends_on:
      - db
    networks:
      - crm-network

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crm
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - crm-network

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/dist:/usr/share/nginx/html:ro
    depends_on:
      - frontend
      - backend
    networks:
      - crm-network

volumes:
  pgdata:
  frontend-build:

networks:
  crm-network: